#!/bin/bash

echo "🔑 Getting JWT Token for Testing"
echo "================================="
echo ""
echo "Step 1: Open this URL in your browser:"
echo ""
echo "  http://localhost:8000/auth/github"
echo ""
echo "Step 2: After GitHub authorization, you'll be redirected to:"
echo ""
echo "  http://localhost:5173/auth/callback?token=LONG_JWT_TOKEN&user=USER_DATA"
echo ""
echo "Step 3: Copy ONLY the token part (the long string after 'token=')"
echo "        It should look like: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MS..."
echo ""
echo "Step 4: Set it in your terminal:"
echo ""
echo '  export JWT_TOKEN="paste-your-token-here"'
echo ""
echo "Step 5: Run the tests:"
echo ""
echo "  ./test-backend-complete.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 TIP: The token is the LONG string (100+ characters)"
echo "    NOT the short 'code' parameter"
echo ""
echo "Example of what to copy:"
echo "  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwid..."
echo "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "         Copy everything after 'token=' until '&user='"
echo ""
